services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db  #
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend 
    ports:
      - "3000:3000" 
    depends_on:
      - web