version: '3.8'  # Asegúrate de que esta línea esté en la parte superior

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Asegúrate de que este puerto esté expuesto

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db  # Asegúrate de que este contenedor dependa del de la base de datos
    environment:
      - PYTHONPATH=/app
